---
- name: Take snapshots of virtual machines
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "vcenter.example.com"
    vcenter_username: "normal_user"
    vcenter_password: "normal_password"
    snapshot_name: "snapshot_name"
    snapshot_description: "snapshot_description"
    snapshot_memory: no
    snapshot_quiesce: yes
    vm_list_file: "vm_list.txt"

  tasks:
  - name: Read list of virtual machines
    slurp:
      src: "{{ vm_list_file }}"
    register: vm_list_data

  - name: Create snapshots
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      snapshot_name: "{{ snapshot_name }}"
      description: "{{ snapshot_description }}"
      memory: "{{ snapshot_memory }}"
      quiesce: "{{ snapshot_quiesce }}"
    loop: "{{ vm_list_data['content'] | b64decode | splitlines() }}"

